# this file is used to build containers locally on develop host.

version: '2'

services:
  postgres:
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: changeme
    image: postgres:11
    ports:
      - "5432:5432"
    volumes:
      - $home/docker/volumes/postgres:/var/lib/postgresql/data




  redis:
    image: redis:3.0
    ports:
      - "6379:6379"